version: '3.9'

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    environment:
      - VIRTUAL_HOST=www.t.com
      - LETSENCRYPT_HOST=www.t.com
      - LETSENCRYPT_EMAIL=luckykenlin@gmail.com
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel
      - services_multiple_site

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
      - services_multiple_site
    external_links:
      - mysql:mysql
      - redis:redis

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    networks:
      - laravel
      - services_multiple_site
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]

  npm:
    image: node:14.15.3
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ 'npm' ]

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel
      - services_multiple_site
    external_links:
      - mysql:mysql
      - redis:redis

networks:
  laravel:
  services_multiple_site:
    external: true