version: '3.9'

services:
  db:
    image: mysql:5.7.29
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - 'mysql:/var/lib/mysql'

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  mysql:
    driver: local
