version: '3.2'

networks:
  proxy:
    driver: bridge

services:

  mkcert:
    image: aegypius/mkcert-for-nginx-proxy
    restart: unless-stopped
    volumes:
      - ./ssl-certs:/app/certs
      - ~/.mozilla/firefox:/root/.mozilla/firefox:rw
      - ~/.pki/nssdb:/root/.pki/nssdb:rw
      - ${CA_STORE:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - /var/run/docker.sock:/var/run/docker.sock:ro

  proxy:
    image: jwilder/nginx-proxy
    networks:
      - proxy
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    restart: unless-stopped
    volumes:
      - ./ssl-certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro